
services:

  client:
    container_name: client_tweets_container
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      server:
        condition: service_started
        restart: true
    networks:
      - my_network

  server:
    container_name: server_tweets_container
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my_network
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_USER=tweets_db
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d tweets_db -U tweets_db" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - '5432:5432'
    networks:
      - my_network
    volumes:
      - ./server/postgres-data:/var/lib/postgresql
      - ./server/my_postgresql.conf:/postgresql.conf
    command: ["postgres", "-c", "config_file=./postgresql.conf"]

networks:
  my_network:
    driver: bridge
