name: Linters
on: [pull_request,push]
jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r hw1/requirements.txt
      - name: black
        run: black  hw1/
      - name: isort
        run: isort --profile black hw1/  
      - name: mypy
        run: mypy hw1/ 
      - name: flake
        run: flake8 hw1/  
      - name: test_httpx
        run: python hw1/test_main.py  
        

