name: Linters
on: [pull_request,push]
jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r py_adv_diploma_for_github/requirements.txt
      - name: black
        run: black  py_adv_diploma_for_github/server/app_tweets/
      - name: isort
      #   run: isort --profile black py_adv_diploma_for_github/server/app_tweets/
      # - name: mypy
        run: mypy py_adv_diploma_for_github/server/app_tweets/ 
      - name: flake
        run: flake8 py_adv_diploma_for_github/server/app_tweets/ 
      # - name: test_httpx
      #   run: python hw1/test_main.py  
        

